services:
  - type: web
    name: taskmanager-api
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: "postgresql+asyncpg://postgres:password@localhost:5432/postgres"
      - key: SECRET_KEY
        value: "change-me-secret"
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: ALEMBIC_DATABASE_URL
        value: "postgresql://postgres:password@localhost:5432/postgres"
